/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "abknbxrmvivutoplgzlg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFia25ieHJtdml2dXRvcGxnemxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NTU4MzksImV4cCI6MjA3MTAzMTgzOX0.DaCrmdnzU_ADoIaZ-Xwj3A-SuIVerUyG29SkbHHfflU"